=== project178/documents-structures/devoirs/exo.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % r "#REQUIRED">
<!ENTITY p "88 g">
<!ENTITY h "0,61 cm">
<!ENTITY la "5,86 cm">
<!ENTITY lo "12,34 cm">
<!ENTITY t "40 h">
<!ENTITY u "unknown">

<!ELEMENT baladeurs (baladeur+)>
<!ELEMENT baladeur (nom, autonomie, poids, stockage, taille)>

<!ATTLIST baladeur id CDATA %r;>
<!ATTLIST baladeur type CDATA %r;>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT autonomie (#PCDATA)>
<!ELEMENT poids (#PCDATA)>
<!ELEMENT stockage (#PCDATA)>

<!ELEMENT taille (hauteur, largeur, longueur)>
<!ELEMENT hauteur (#PCDATA)>
<!ELEMENT largeur (#PCDATA)>
<!ELEMENT longueur (#PCDATA)>

=== project178/documents-structures/devoirs/exo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE baladeurs SYSTEM "exo.dtd">

<baladeurs>
    <baladeur id="1" type="mp3, mp4">
        <nom>Apple iPod Touch 32 Go Bleu</nom>
        <autonomie>&t;</autonomie>
        <poids>&p;</poids>
        <stockage>32 Go</stockage>
        <taille>
            <hauteur>&h;</hauteur>
            <largeur>&la;</largeur>
            <longueur>&lo;</longueur>
        </taille>
    </baladeur>
    <baladeur id="2" type="mp3, mp4">
        <nom>Apple iPod Touch 64 Go Silver - Argent</nom>
        <autonomie>&t;</autonomie>
        <poids>&p;</poids>
        <stockage>64 Go</stockage>
        <taille>
            <hauteur>&h;</hauteur>
            <largeur>&la;</largeur>
            <longueur>&lo;</longueur>
        </taille>
    </baladeur>
    <baladeur id="3" type="mp3, mp4">
        <nom>Apple iPod Touch 128 Go Argent</nom>
        <autonomie>&t;</autonomie>
        <poids>&p;</poids>
        <stockage>128 Go</stockage>
        <taille>
            <hauteur>&h;</hauteur>
            <largeur>&la;</largeur>
            <longueur>&lo;</longueur>
        </taille>
    </baladeur>
    <baladeur id="4" type="mp3">
        <nom>Lecteur Audio Bluetooth Sony NW-A55L Haute RÃ©solution 16 Go Noir</nom>
        <autonomie>&u;</autonomie>
        <poids>99 g</poids>
        <stockage>16 Go</stockage>
        <taille>
            <hauteur>1,08 cm</hauteur>
            <largeur>5,57 cm</largeur>
            <longueur>9,73 cm</longueur>
        </taille>
    </baladeur>
    <baladeur id="4" type="mp3">
        <nom>Fiio M11 Noir - Baladeur Audiophile</nom>
        <autonomie>&u;</autonomie>
        <poids>0,15 g</poids>
        <stockage>&u;</stockage>
        <taille>
            <hauteur>&u;</hauteur>
            <largeur>&u;</largeur>
            <longueur>&u;</longueur>
        </taille>
    </baladeur>
</baladeurs>
